// https://github.com/codeplea/Hands-On-Network-Programming-with-C/blob/master/chap03/chap03.h
#include <arpa/inet.h>
#include <errno.h>
#include <netdb.h>
#include <netinet/in.h>
#include <stdio.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>
